// Mocks generated by Mockito 5.4.6 from annotations
// in ride_hailing_driver/test/unit/location_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:ride_hailing_driver/core/network/connectivity_service.dart'
    as _i6;
import 'package:ride_hailing_driver/features/location/domain/entities/driver_location.dart'
    as _i8;
import 'package:ride_hailing_driver/features/location/domain/repositories/location_repository.dart'
    as _i7;
import 'package:ride_hailing_driver/features/location/domain/usecases/start_tracking_usecase.dart'
    as _i2;
import 'package:ride_hailing_driver/features/location/domain/usecases/stop_tracking_usecase.dart'
    as _i4;
import 'package:ride_hailing_driver/features/location/domain/usecases/upload_pending_locations_usecase.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [StartTrackingUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockStartTrackingUseCase extends _i1.Mock
    implements _i2.StartTrackingUseCase {
  MockStartTrackingUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.TrackingStartResult> call(String? tripId) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [tripId],
        ),
        returnValue: _i3.Future<_i2.TrackingStartResult>.value(
            _i2.TrackingStartResult.started),
      ) as _i3.Future<_i2.TrackingStartResult>);
}

/// A class which mocks [StopTrackingUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockStopTrackingUseCase extends _i1.Mock
    implements _i4.StopTrackingUseCase {
  MockStopTrackingUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [UploadPendingLocationsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUploadPendingLocationsUseCase extends _i1.Mock
    implements _i5.UploadPendingLocationsUseCase {
  MockUploadPendingLocationsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<int> get pendingCount => (super.noSuchMethod(
        Invocation.getter(#pendingCount),
        returnValue: _i3.Stream<int>.empty(),
      ) as _i3.Stream<int>);

  @override
  _i3.Future<int> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);
}

/// A class which mocks [ConnectivityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivityService extends _i1.Mock
    implements _i6.ConnectivityService {
  MockConnectivityService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: false,
      ) as bool);

  @override
  _i3.Stream<bool> get onConnectivityChanged => (super.noSuchMethod(
        Invocation.getter(#onConnectivityChanged),
        returnValue: _i3.Stream<bool>.empty(),
      ) as _i3.Stream<bool>);

  @override
  _i3.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> checkConnectivity() => (super.noSuchMethod(
        Invocation.method(
          #checkConnectivity,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [LocationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationRepository extends _i1.Mock
    implements _i7.LocationRepository {
  MockLocationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<int> get pendingLocationCount => (super.noSuchMethod(
        Invocation.getter(#pendingLocationCount),
        returnValue: _i3.Stream<int>.empty(),
      ) as _i3.Stream<int>);

  @override
  bool get isTracking => (super.noSuchMethod(
        Invocation.getter(#isTracking),
        returnValue: false,
      ) as bool);

  @override
  _i3.Stream<_i8.DriverLocation> get locationStream => (super.noSuchMethod(
        Invocation.getter(#locationStream),
        returnValue: _i3.Stream<_i8.DriverLocation>.empty(),
      ) as _i3.Stream<_i8.DriverLocation>);

  @override
  _i3.Stream<_i8.DriverLocation> get foregroundLocationStream =>
      (super.noSuchMethod(
        Invocation.getter(#foregroundLocationStream),
        returnValue: _i3.Stream<_i8.DriverLocation>.empty(),
      ) as _i3.Stream<_i8.DriverLocation>);

  @override
  _i3.Future<void> startTracking(String? tripId) => (super.noSuchMethod(
        Invocation.method(
          #startTracking,
          [tripId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> resumeTracking(String? tripId) => (super.noSuchMethod(
        Invocation.method(
          #resumeTracking,
          [tripId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> stopTracking() => (super.noSuchMethod(
        Invocation.method(
          #stopTracking,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> saveLocationLocally(_i8.DriverLocation? location) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveLocationLocally,
          [location],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<int> uploadPendingLocations() => (super.noSuchMethod(
        Invocation.method(
          #uploadPendingLocations,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> getPendingCount() => (super.noSuchMethod(
        Invocation.method(
          #getPendingCount,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<String?> getActiveTripId() => (super.noSuchMethod(
        Invocation.method(
          #getActiveTripId,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<bool> requestPermissions() => (super.noSuchMethod(
        Invocation.method(
          #requestPermissions,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  void setCountryCode(String? code) => super.noSuchMethod(
        Invocation.method(
          #setCountryCode,
          [code],
        ),
        returnValueForMissingStub: null,
      );
}
